
/* ----------------------------------------------------------------- */

#ifndef _arimac
#define _arimac

#include <stdint.h>
#include <alloca.h>

/* ----------------------------------------------------------------- */

typedef uint8_t  uchar ;
typedef uint16_t ushort ;
typedef uint32_t ulong ;

#define numberof(x)	( sizeof ( x ) / sizeof ( * ( x ) ) )
#define global


/* ----------------------------------------------------------------- */

#endif

/* ----------------------------------------------------------------- */
